version: '3'

services: 

  #Database
  mongo:
    image: mongo
    container_name: '${NAME_API}_mongo'
    environment: 
      MONGO_INITDB_ROOT_USERNAME: '${MDB_ROOT_USERNAME}'
      MONGO_INITDB_ROOT_PASSWORD: '${MDB_ROOT_PASSWORD}'
      MONGO_INITDB_DATABASE: '${MDB_DATABASE}'
    ports:
      - 27017:27017
    volumes: 
      - db_data:/data/db
  
  mongo-express:
    image: mongo-express
    container_name: '${NAME_API}_mongo_express'
    ports:
     - 8081:8081
    environment: 
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin      
      ME_CONFIG_MONGODB_ADMINUSERNAME: '${MDB_ROOT_USERNAME}'
      ME_CONFIG_MONGODB_ADMINPASSWORD: '${MDB_ROOT_PASSWORD}'
      ME_CONFIG_MONGODB_URL: mongodb://${MDB_ROOT_USERNAME}:${MDB_ROOT_PASSWORD}@mongo:27017/
    depends_on: 
      - mongo

volumes: 
  db_data: { }